name = "Sandat"
license = "MIT"
licenselink = "https://github.com/dyogi24/hugo-sandat/blob/main/LICENSE"
description = "simple HUGO Theme For Blog Website"
homepage = "https://github.com/dyogi24"
tags = ["blog", "minimalist", "paper", "clean", "simple", "light", "writing"]
features = ["blog", "responsive"]
min_version = "0.41"

[author]
  name = "Yogi Indrawan"
  homepage = "https://github.com/dyogi24/hugo-sandat"


